import Head from 'next/head'
import {ProductCard,Categories,PostWidget} from '../components/index'
import {getProducts} from '../services'
import {NewProducts} from '../sections/'

 
export default function Home({products}) {

  return (
    <div className='container mx-auto px-10 mb-8'>
      <NewProducts/>
      <Head>
        <title>mabrayo electricals</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className='gapp'>
        <div className='list'>
        {products.map((product)=> <ProductCard key={product.node.id} product={product.node}/>
      )}
        </div>
        <div className='where'>
          <div className='lg:sticky relative top-8'>
            <PostWidget/>
            <Categories/>
          </div>

        </div>
      </div>
     
    </div>
  )
}
export async function getStaticProps(){
  const products = (await getProducts())||[]
  return {
    props:{products},
    revalidate:10
  }
}